extends: stylelint-config-standard

ignoreFiles:
  - coverage/**/*.css
  - client/css/bootstrap.css

rules:
  indentation: tab
  number-leading-zero: never
  selector-pseudo-element-colon-notation: single
